### PR TITLE
move tests to suitable packages

### PR DESCRIPTION
**Pull request by alekseybarabanov**

### CODE REVIEW

**Comment by Quantification** [comment]
Ya ten vremenrm izmenil kod. On ne propadet pri merge?

**Comment by alekseybarabanov** [comment]
No, it won't be cut normally. When you proceed merge, all possible conflicts are to be resolved and normally the automatical merge is OK. Anywhere, after merge has finished you may see the difference. To be sure, you may compare your code after merge with code before it and correct missing parts.

**Comment by Quantification** [comment]
Why did you put the test classes to different subdirs?  What value does it add? There is not enough files to make a mess.

**Comment by Quantification** [comment]
Maybe I misunderstand something: I think it is necessary to merge all branches? If no, then please excuse me: let there be two forks, no problem. Sorry, I'm not so familiar with gitHub.

**Comment by alekseybarabanov** [comment]
1. Moving tests to different packages is just a matter of convenience. We have this type of structure in technical specification. I see that you are going to have one class per each asset type. The possible situation is that input data for different tests for one type of asset are very different. In this case it is reasonable to have different test classes to give explicit separation of the input data, just not to mess static variables in single file. Common parts of tests may be moved into separate shared class. I personally prefer to keep in one test class tests that are very close by meaning, and have different classes otherwise. If you don't accept it, no problem, just reject those changes.
2. I don't have permission to commit into your branch directly. Possibly you could give it to me. This is the only reason I made this fork.

**Comment by Quantification** [comment]
OK. Granted you some rights, hope it'll permit you to commit.

**Pull request merged**
